title: Dogwood
copyright: OpenStreetMap US
permalink: /:title/
# Include "future" posts so that upcoming events will display. Posts cannot be scheduled to automatically
# publish at a certain time with Jekyll alone.
logo: /dogwoods.svg
future: true
timezone: America/New_York
github: osmus
mastodon: https://en.osm.town/@OpenStreetMapUS
twitter: openstreetmapus
youtube_page: channel/UCQpS2iHNVR-_6nAxt87nwCw
facebook: openstreetmap.us
instagram: openstreetmapus
linkedin: company/openstreetmap-us
links:
  - link: https://github.com/osmus/dogwood
    label: Use Me!
    class: no-cond
    a_class: button bordered
plugins:
  - jekyll-archives
  - jekyll-include-cache
jekyll-archives:
  enabled:
    - tags
    - month
    - year
  layouts:
    tag: archives/posts-tag
    year: archives/posts-year
    month: archives/month
  permalinks:
    tag: '/tags/:name/'
    month: '/:year/:month/'
    year: '/:year/'
date_format: "%b %e, %Y"